version: '3.8'
services:
  payment-service:
    image: vunjash/stripe-backend:latest
    ports:
      - "3001:3000"
    environment:
      APP_BASE_URL: http://localhost:3001
      STRIPE_PUBLISHABLE_KEY: pk_test_51RQqC7BHSqmERpQugTEM7dbOj0n7ZthxZ8zCmNxl6sVjUmx5AznO8i7pZRiMHcpAl3ggKd8uoPgcFSb9FroOW6N900XKh5XKev
      STRIPE_SECRET_KEY: sk_test_51RQqC7BHSqmERpQub8mirJaaXuGzfJtrWUVsbl5QsiiMZQzlWmOwOaxmAU7MdpjmXS8e6C84i7oyGT4GjDPXiGM100TMsEvMkA
      STRIPE_WEBHOOK_SECRET: whsec_b26df86e8649a194fcaaf5d9b2c166e3d456b17fd2c45ef64830e73023d7b2a9
      DATABASE_URL: postgres://doadmin:AVNS_UZNzzzHCje7TJO1TmhN@stripe-payment-gw-do-user-18671628-0.k.db.ondigitalocean.com:25060/defaultdb
      STRIPE_PRICE_BASIC_PLAN_ID: price_1RsMolBHSqmERpQuEsSlB8cQ
      STRIPE_PRICE_PREMIUM_PLAN_ID: price_1RTkpPBHSqmERpQu44sl02EJ
      BILLING_SERVICE_URL: admin-service:7001/api/v1/billings
      BILLING_SERVICE_TOKEN: 1002485363
      CORS_ORIGIN: http://localhost:8084
    networks:
      - soa-net
    volumes:
      - ./storage:/storage

networks:
  soa-net:
    driver: bridge
